#!/usr/bin/env sh
# dependencies/setup.sh -- one-time toolchain setup. Needs only sh, curl and tar.
#
# Downloads a pinned pixi into dependencies/bin/, builds the environment
# described by the pixi.toml + pixi.lock next to this script (verilator, make,
# g++, yosys, ...), and writes dependencies/toolchain.mk so the project's
# Makefiles use those tools automatically. Nothing goes into system
# directories and no sudo is needed. Safe to re-run -- and re-run it whenever
# pixi.lock changes (make will tell you).
#
# Afterwards:
#   make regress
set -eu

PIXI_VERSION=0.80.0

DEPS=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
cd "$DEPS"
BIN="$DEPS/bin/pixi"

case "$(uname -s)-$(uname -m)" in
    Linux-x86_64)  TARGET=x86_64-unknown-linux-musl ;;
    Linux-aarch64) TARGET=aarch64-unknown-linux-musl ;;
    Darwin-x86_64) TARGET=x86_64-apple-darwin ;;
    Darwin-arm64)  TARGET=aarch64-apple-darwin ;;
    *) echo "setup: unsupported platform $(uname -s)-$(uname -m) -- on Windows, run this inside WSL" >&2
       exit 1 ;;
esac

if [ ! -x "$BIN" ] || [ "$("$BIN" --version 2>/dev/null)" != "pixi $PIXI_VERSION" ]; then
    echo "setup: downloading pixi $PIXI_VERSION ($TARGET)..." >&2
    mkdir -p "$DEPS/bin"
    curl -fsSL "https://github.com/prefix-dev/pixi/releases/download/v$PIXI_VERSION/pixi-$TARGET.tar.gz" \
        | tar -xz -C "$DEPS/bin" pixi
fi

# A repo on a Windows drive (WSL /mnt/c) is slow and awkward for a ~1 GB env,
# so keep the env in the Linux-side cache instead. Config stays per-checkout.
case "$DEPS" in
    /mnt/[a-z]/*) "$BIN" config set --local detached-environments true ;;
esac

# --locked: refuse to run if pixi.toml and pixi.lock disagree, so everyone
# gets exactly the versions that were committed.
"$BIN" install --locked

# Tell make where the pinned tools live. config.mk puts this directory first on
# PATH, and compares the lock checksum so a changed pixi.lock is caught.
PREFIX=$("$BIN" run --locked printenv CONDA_PREFIX)
if [ ! -x "$PREFIX/bin/verilator" ]; then
    echo "setup: expected verilator under '$PREFIX/bin' -- env looks broken" >&2
    exit 1
fi
LOCKSUM=$(cksum < "$DEPS/pixi.lock" | cut -d' ' -f1)
cat > "$DEPS/toolchain.mk" <<EOF
# generated by dependencies/setup.sh -- do not edit, do not commit
TOOLCHAIN_BIN  := $PREFIX/bin
TOOLCHAIN_LOCK := $LOCKSUM
EOF

echo "setup: done.  Try:  make regress" >&2
