// Generated by export.py. Do not edit by hand.
// Regenerate with: python export.py <weights.json> --verilog weights.vh

`ifndef CNN_WEIGHTS_VH
`define CNN_WEIGHTS_VH

localparam integer WEIGHT_BITS = 4;   // int4, stored biased by 8
localparam integer ACT_BITS    = 4;   // uint4, 0..15
localparam integer ACC_BITS    = 16;  // signed accumulator
localparam integer OUT_BITS    = 6;   // 0..63
localparam integer BIAS_BITS   = 8;
localparam integer KERNEL      = 3;
localparam integer NUM_LAYERS  = 3;
localparam integer MAX_CH      = 8;
localparam integer RECEPTIVE   = 7;  // 7x7, for the line buffers

// Layer 0: 1 -> 8 channels, 72 MACs/pixel, shift 3
localparam integer L0_IN = 1;
localparam integer L0_OUT = 8;
localparam [3:0] L0_SHIFT = 4'd3;
// Weights are BIASED: stored u = w + 8, so 0..15 unsigned.
// Recover the signed weight as (u - 8), or use the
// decomposition sum(w*a) = sum(u*a) - 8*sum(a).
localparam [3:0] L0_W [0:71] = '{
    4'd9, 4'd11, 4'd9, 4'd7, 4'd4, 4'd10, 4'd11, 4'd10, 4'd12, 4'd10, 4'd10, 4'd11, 4'd12,
    4'd12, 4'd9, 4'd13, 4'd6, 4'd11, 4'd10, 4'd14, 4'd10, 4'd6, 4'd7, 4'd14, 4'd5, 4'd8,
    4'd7, 4'd13, 4'd5, 4'd11, 4'd8, 4'd3, 4'd10, 4'd9, 4'd11, 4'd9, 4'd7, 4'd6, 4'd8, 4'd13,
    4'd3, 4'd8, 4'd11, 4'd11, 4'd11, 4'd6, 4'd11, 4'd11, 4'd5, 4'd3, 4'd11, 4'd8, 4'd9,
    4'd10, 4'd7, 4'd4, 4'd7, 4'd5, 4'd12, 4'd12, 4'd8, 4'd12, 4'd10, 4'd8, 4'd11, 4'd9,
    4'd14, 4'd5, 4'd7, 4'd8, 4'd8, 4'd4
};
localparam signed [7:0] L0_B [0:7] = '{-8'sd8, -8'sd15, 8'sd6, 8'sd7, 8'sd10, 8'sd19, 8'sd13, 8'sd16};
// Layer 1: 8 -> 8 channels, 576 MACs/pixel, shift 4
localparam integer L1_IN = 8;
localparam integer L1_OUT = 8;
localparam [3:0] L1_SHIFT = 4'd4;
// Weights are BIASED: stored u = w + 8, so 0..15 unsigned.
// Recover the signed weight as (u - 8), or use the
// decomposition sum(w*a) = sum(u*a) - 8*sum(a).
localparam [3:0] L1_W [0:575] = '{
    4'd9, 4'd8, 4'd6, 4'd6, 4'd8, 4'd9, 4'd9, 4'd7, 4'd7, 4'd9, 4'd9, 4'd8, 4'd9, 4'd11,
    4'd6, 4'd9, 4'd10, 4'd8, 4'd8, 4'd7, 4'd7, 4'd6, 4'd7, 4'd10, 4'd10, 4'd8, 4'd8, 4'd8,
    4'd7, 4'd8, 4'd10, 4'd4, 4'd10, 4'd7, 4'd11, 4'd5, 4'd9, 4'd5, 4'd8, 4'd7, 4'd13, 4'd6,
    4'd7, 4'd9, 4'd8, 4'd9, 4'd7, 4'd7, 4'd9, 4'd10, 4'd10, 4'd10, 4'd6, 4'd8, 4'd8, 4'd10,
    4'd7, 4'd10, 4'd1, 4'd8, 4'd8, 4'd10, 4'd10, 4'd8, 4'd8, 4'd9, 4'd6, 4'd15, 4'd5, 4'd9,
    4'd7, 4'd7, 4'd7, 4'd12, 4'd10, 4'd3, 4'd9, 4'd7, 4'd6, 4'd8, 4'd8, 4'd7, 4'd11, 4'd11,
    4'd7, 4'd8, 4'd14, 4'd5, 4'd7, 4'd10, 4'd8, 4'd8, 4'd9, 4'd5, 4'd13, 4'd7, 4'd7, 4'd7,
    4'd8, 4'd8, 4'd8, 4'd10, 4'd7, 4'd6, 4'd8, 4'd5, 4'd11, 4'd7, 4'd9, 4'd7, 4'd11, 4'd7,
    4'd3, 4'd7, 4'd6, 4'd6, 4'd11, 4'd9, 4'd11, 4'd9, 4'd8, 4'd14, 4'd7, 4'd8, 4'd10, 4'd8,
    4'd8, 4'd12, 4'd8, 4'd6, 4'd7, 4'd9, 4'd6, 4'd8, 4'd8, 4'd8, 4'd6, 4'd8, 4'd8, 4'd8,
    4'd8, 4'd8, 4'd8, 4'd8, 4'd9, 4'd5, 4'd12, 4'd8, 4'd9, 4'd10, 4'd7, 4'd7, 4'd6, 4'd10,
    4'd8, 4'd12, 4'd8, 4'd9, 4'd9, 4'd6, 4'd5, 4'd9, 4'd11, 4'd9, 4'd8, 4'd10, 4'd10, 4'd9,
    4'd5, 4'd6, 4'd7, 4'd8, 4'd5, 4'd9, 4'd10, 4'd3, 4'd12, 4'd7, 4'd8, 4'd8, 4'd9, 4'd5,
    4'd10, 4'd9, 4'd2, 4'd11, 4'd7, 4'd9, 4'd9, 4'd8, 4'd4, 4'd7, 4'd13, 4'd10, 4'd6, 4'd7,
    4'd7, 4'd7, 4'd10, 4'd10, 4'd8, 4'd5, 4'd3, 4'd7, 4'd6, 4'd8, 4'd9, 4'd6, 4'd6, 4'd11,
    4'd11, 4'd8, 4'd8, 4'd8, 4'd6, 4'd7, 4'd4, 4'd5, 4'd9, 4'd9, 4'd11, 4'd8, 4'd6, 4'd5,
    4'd8, 4'd8, 4'd9, 4'd9, 4'd6, 4'd4, 4'd11, 4'd4, 4'd5, 4'd10, 4'd8, 4'd8, 4'd8, 4'd7,
    4'd13, 4'd7, 4'd6, 4'd6, 4'd9, 4'd7, 4'd6, 4'd8, 4'd8, 4'd12, 4'd8, 4'd8, 4'd6, 4'd9,
    4'd6, 4'd6, 4'd10, 4'd10, 4'd5, 4'd11, 4'd8, 4'd6, 4'd9, 4'd10, 4'd11, 4'd12, 4'd14,
    4'd15, 4'd8, 4'd9, 4'd11, 4'd10, 4'd7, 4'd8, 4'd9, 4'd5, 4'd14, 4'd7, 4'd10, 4'd11, 4'd8,
    4'd10, 4'd7, 4'd10, 4'd11, 4'd4, 4'd11, 4'd9, 4'd8, 4'd9, 4'd10, 4'd8, 4'd11, 4'd8, 4'd7,
    4'd11, 4'd10, 4'd11, 4'd12, 4'd11, 4'd10, 4'd14, 4'd10, 4'd8, 4'd11, 4'd13, 4'd11, 4'd13,
    4'd10, 4'd11, 4'd11, 4'd7, 4'd4, 4'd9, 4'd3, 4'd9, 4'd10, 4'd11, 4'd9, 4'd8, 4'd9, 4'd3,
    4'd9, 4'd9, 4'd8, 4'd8, 4'd6, 4'd5, 4'd5, 4'd9, 4'd6, 4'd11, 4'd11, 4'd11, 4'd8, 4'd4,
    4'd7, 4'd8, 4'd4, 4'd5, 4'd8, 4'd5, 4'd7, 4'd6, 4'd5, 4'd7, 4'd6, 4'd7, 4'd6, 4'd8, 4'd7,
    4'd8, 4'd11, 4'd8, 4'd8, 4'd8, 4'd9, 4'd3, 4'd7, 4'd7, 4'd6, 4'd1, 4'd10, 4'd9, 4'd7,
    4'd8, 4'd2, 4'd6, 4'd9, 4'd11, 4'd8, 4'd10, 4'd4, 4'd11, 4'd9, 4'd11, 4'd7, 4'd10, 4'd9,
    4'd9, 4'd8, 4'd8, 4'd7, 4'd12, 4'd3, 4'd9, 4'd7, 4'd11, 4'd8, 4'd7, 4'd11, 4'd9, 4'd9,
    4'd0, 4'd9, 4'd9, 4'd9, 4'd7, 4'd11, 4'd9, 4'd9, 4'd7, 4'd1, 4'd12, 4'd8, 4'd9, 4'd7,
    4'd8, 4'd9, 4'd8, 4'd8, 4'd0, 4'd10, 4'd8, 4'd11, 4'd10, 4'd9, 4'd9, 4'd7, 4'd10, 4'd9,
    4'd8, 4'd6, 4'd6, 4'd9, 4'd5, 4'd6, 4'd7, 4'd8, 4'd3, 4'd12, 4'd7, 4'd11, 4'd9, 4'd11,
    4'd8, 4'd7, 4'd9, 4'd3, 4'd8, 4'd9, 4'd8, 4'd7, 4'd9, 4'd9, 4'd7, 4'd10, 4'd9, 4'd11,
    4'd7, 4'd7, 4'd5, 4'd8, 4'd9, 4'd4, 4'd13, 4'd8, 4'd7, 4'd11, 4'd12, 4'd8, 4'd8, 4'd12,
    4'd8, 4'd8, 4'd0, 4'd10, 4'd10, 4'd5, 4'd12, 4'd11, 4'd12, 4'd8, 4'd7, 4'd2, 4'd14, 4'd9,
    4'd5, 4'd9, 4'd12, 4'd13, 4'd10, 4'd10, 4'd1, 4'd10, 4'd12, 4'd11, 4'd10, 4'd10, 4'd11,
    4'd9, 4'd12, 4'd13, 4'd2, 4'd8, 4'd5, 4'd8, 4'd7, 4'd11, 4'd9, 4'd8, 4'd7, 4'd15, 4'd10,
    4'd10, 4'd10, 4'd12, 4'd9, 4'd9, 4'd10, 4'd4, 4'd6, 4'd7, 4'd3, 4'd4, 4'd13, 4'd12, 4'd9,
    4'd10, 4'd10, 4'd7, 4'd7, 4'd4, 4'd4, 4'd12, 4'd9, 4'd8, 4'd10, 4'd11, 4'd6, 4'd9, 4'd3,
    4'd7, 4'd10, 4'd8, 4'd10, 4'd9, 4'd4, 4'd8, 4'd8, 4'd8, 4'd6, 4'd10, 4'd9, 4'd9, 4'd8,
    4'd3, 4'd9, 4'd9, 4'd7, 4'd8, 4'd5, 4'd8, 4'd9, 4'd10, 4'd4, 4'd11, 4'd8, 4'd10, 4'd10,
    4'd10, 4'd9, 4'd9, 4'd8, 4'd2, 4'd7, 4'd9, 4'd7, 4'd7, 4'd10, 4'd8, 4'd10, 4'd8, 4'd15,
    4'd7, 4'd7, 4'd7, 4'd11
};
localparam signed [7:0] L1_B [0:7] = '{8'sd11, 8'sd17, 8'sd13, 8'sd15, 8'sd1, 8'sd16, -8'sd1, 8'sd19};
// Layer 2: 8 -> 1 channels, 72 MACs/pixel, shift 5
localparam integer L2_IN = 8;
localparam integer L2_OUT = 1;
localparam [3:0] L2_SHIFT = 4'd5;
// Weights are BIASED: stored u = w + 8, so 0..15 unsigned.
// Recover the signed weight as (u - 8), or use the
// decomposition sum(w*a) = sum(u*a) - 8*sum(a).
localparam [3:0] L2_W [0:71] = '{
    4'd8, 4'd9, 4'd7, 4'd11, 4'd12, 4'd2, 4'd7, 4'd4, 4'd11, 4'd10, 4'd10, 4'd12, 4'd1, 4'd9,
    4'd9, 4'd6, 4'd4, 4'd11, 4'd7, 4'd10, 4'd8, 4'd10, 4'd6, 4'd12, 4'd8, 4'd0, 4'd8, 4'd8,
    4'd5, 4'd10, 4'd5, 4'd9, 4'd15, 4'd7, 4'd5, 4'd7, 4'd8, 4'd11, 4'd9, 4'd11, 4'd7, 4'd10,
    4'd10, 4'd9, 4'd10, 4'd8, 4'd11, 4'd8, 4'd10, 4'd0, 4'd7, 4'd9, 4'd9, 4'd9, 4'd9, 4'd7,
    4'd11, 4'd10, 4'd0, 4'd7, 4'd8, 4'd9, 4'd8, 4'd14, 4'd11, 4'd9, 4'd10, 4'd7, 4'd6, 4'd8,
    4'd2, 4'd6
};
localparam signed [7:0] L2_B [0:0] = '{-8'sd1};

// The whole payload as 253 x 12-bit config words, LSB first.
// 3028 significant bits.
localparam integer CFG_WORDS = 253;
localparam [11:0] DEF_CFG_WORDS [0:252] = '{
    12'h9B9, 12'hA47, 12'hCAB, 12'hBAA, 12'h9CC, 12'hB6D, 12'hAEA, 12'hE76, 12'h785, 12'hB5D,
    12'hA38, 12'h9B9, 12'h867, 12'h83D, 12'hBBB, 12'hBB6, 12'hB35, 12'hA98, 12'h747, 12'hCC5,
    12'hAC8, 12'h9B8, 12'h75E, 12'h488, 12'h1F8, 12'h06F, 12'hA07, 12'h130, 12'h00D, 12'h931,
    12'h668, 12'h998, 12'h977, 12'h989, 12'h96B, 12'h88A, 12'h677, 12'hAA7, 12'h888, 12'hA87,
    12'h7A4, 12'h95B, 12'h785, 12'h76D, 12'h989, 12'h977, 12'hAAA, 12'h886, 12'hA7A, 12'h881,
    12'h8AA, 12'h698, 12'h95F, 12'h777, 12'h3AC, 12'h679, 12'h788, 12'h7BB, 12'h5E8, 12'h8A7,
    12'h598, 12'h77D, 12'h887, 12'h7A8, 12'h586, 12'h97B, 12'h7B7, 12'h673, 12'h9B6, 12'h89B,
    12'h87E, 12'h88A, 12'h68C, 12'h697, 12'h888, 12'h886, 12'h888, 12'h988, 12'h8C5, 12'h7A9,
    12'hA67, 12'h8C8, 12'h699, 12'hB95, 12'hA89, 12'h59A, 12'h876, 12'hA95, 12'h7C3, 12'h988,
    12'h9A5, 12'h7B2, 12'h899, 12'hD74, 12'h76A, 12'hA77, 12'h58A, 12'h673, 12'h698, 12'hBB6,
    12'h888, 12'h476, 12'h995, 12'h68B, 12'h885, 12'h699, 12'h4B4, 12'h8A5, 12'h788, 12'h67D,
    12'h796, 12'h886, 12'h88C, 12'h696, 12'hAA6, 12'h8B5, 12'hA96, 12'hECB, 12'h98F, 12'h7AB,
    12'h598, 12'hA7E, 12'hA8B, 12'hBA7, 12'h9B4, 12'hA98, 12'h8B8, 12'hAB7, 12'hBCB, 12'hAEA,
    12'hDB8, 12'hADB, 12'h7BB, 12'h394, 12'hBA9, 12'h989, 12'h993, 12'h688, 12'h955, 12'hBB6,
    12'h48B, 12'h487, 12'h585, 12'h567, 12'h767, 12'h786, 12'h8B8, 12'h988, 12'h773, 12'hA16,
    12'h879, 12'h962, 12'hA8B, 12'h9B4, 12'hA7B, 12'h899, 12'hC78, 12'h793, 12'h78B, 12'h99B,
    12'h990, 12'hB79, 12'h799, 12'h8C1, 12'h879, 12'h889, 12'h8A0, 12'h9AB, 12'hA79, 12'h689,
    12'h596, 12'h876, 12'h7C3, 12'hB9B, 12'h978, 12'h983, 12'h978, 12'hA79, 12'h7B9, 12'h857,
    12'hD49, 12'hB78, 12'h88C, 12'h88C, 12'hAA0, 12'hBC5, 12'h78C, 12'h9E2, 12'hC95, 12'hAAD,
    12'hCA1, 12'hAAB, 12'hC9B, 12'h82D, 12'h785, 12'h89B, 12'hAF7, 12'hCAA, 12'hA99, 12'h764,
    12'hD43, 12'hA9C, 12'h77A, 12'hC44, 12'hA89, 12'h96B, 12'hA73, 12'h9A8, 12'h884, 12'hA68,
    12'h899, 12'h993, 12'h587, 12'hA98, 12'h8B4, 12'hAAA, 12'h899, 12'h972, 12'hA77, 12'h8A8,
    12'h77F, 12'hBB7, 12'h110, 12'hF0D, 12'h010, 12'hF10, 12'h13F, 12'h984, 12'hCB7, 12'h472,
    12'hAAB, 12'h91C, 12'h469, 12'hA7B, 12'h6A8, 12'h08C, 12'h588, 12'h95A, 12'h57F, 12'hB87,
    12'h7B9, 12'h9AA, 12'hB8A, 12'h0A8, 12'h997, 12'h799, 12'h0AB, 12'h987, 12'hBE8, 12'h7A9,
    12'h286, 12'hFF6, 12'h005
};

`endif
