// Generated by export.py. Do not edit by hand.
// Regenerate with: python export.py <weights.json> --verilog weights.vh

`ifndef CNN_WEIGHTS_VH
`define CNN_WEIGHTS_VH

localparam integer WEIGHT_BITS = 4;   // int4, stored biased by 8
localparam integer ACT_BITS    = 4;   // uint4, 0..15
localparam integer ACC_BITS    = 16;  // signed accumulator
localparam integer OUT_BITS    = 6;   // 0..63
localparam integer BIAS_BITS   = 8;
localparam integer KERNEL      = 3;
localparam integer NUM_LAYERS  = 3;
localparam integer MAX_CH      = 8;
localparam integer RECEPTIVE   = 7;  // 7x7, for the line buffers

// Layer 0: 1 -> 8 channels, 72 MACs/pixel, shift 2
localparam integer L0_IN = 1;
localparam integer L0_OUT = 8;
localparam [3:0] L0_SHIFT = 4'd2;
// Weights are BIASED: stored u = w + 8, so 0..15 unsigned.
// Recover the signed weight as (u - 8), or use the
// decomposition sum(w*a) = sum(u*a) - 8*sum(a).
localparam [3:0] L0_W [0:71] = '{
    4'd5, 4'd12, 4'd10, 4'd5, 4'd11, 4'd8, 4'd8, 4'd7, 4'd9, 4'd8, 4'd6, 4'd7, 4'd9, 4'd10, 
    4'd9, 4'd10, 4'd7, 4'd9, 4'd11, 4'd8, 4'd7, 4'd10, 4'd11, 4'd6, 4'd9, 4'd8, 4'd4, 4'd7, 
    4'd4, 4'd10, 4'd5, 4'd3, 4'd9, 4'd10, 4'd10, 4'd12, 4'd12, 4'd7, 4'd7, 4'd9, 4'd5, 4'd9,
     4'd11, 4'd6, 4'd7, 4'd9, 4'd10, 4'd9, 4'd8, 4'd14, 4'd9, 4'd7, 4'd2, 4'd7, 4'd9, 4'd10,
     4'd9, 4'd10, 4'd7, 4'd5, 4'd8, 4'd6, 4'd7, 4'd8, 4'd7, 4'd8, 4'd9, 4'd10, 4'd10, 4'd9, 
    4'd7, 4'd8
};
localparam signed [7:0] L0_B [0:7] = '{8'sd2, 8'sd0, -8'sd3, -8'sd9, 8'sd3, 8'sd4, -8'sd5, 8'sd1};
// Layer 1: 8 -> 8 channels, 576 MACs/pixel, shift 3
localparam integer L1_IN = 8;
localparam integer L1_OUT = 8;
localparam [3:0] L1_SHIFT = 4'd3;
// Weights are BIASED: stored u = w + 8, so 0..15 unsigned.
// Recover the signed weight as (u - 8), or use the
// decomposition sum(w*a) = sum(u*a) - 8*sum(a).
localparam [3:0] L1_W [0:575] = '{
    4'd7, 4'd10, 4'd9, 4'd5, 4'd9, 4'd10, 4'd8, 4'd9, 4'd9, 4'd5, 4'd5, 4'd8, 4'd11, 4'd9, 4
    'd11, 4'd9, 4'd9, 4'd9, 4'd3, 4'd8, 4'd9, 4'd5, 4'd7, 4'd9, 4'd4, 4'd8, 4'd8, 4'd0, 4'd4
    , 4'd7, 4'd4, 4'd7, 4'd7, 4'd6, 4'd10, 4'd8, 4'd10, 4'd7, 4'd8, 4'd8, 4'd3, 4'd9, 4'd8, 
    4'd5, 4'd10, 4'd2, 4'd5, 4'd6, 4'd10, 4'd10, 4'd10, 4'd8, 4'd12, 4'd7, 4'd10, 4'd10, 4'd
    11, 4'd4, 4'd7, 4'd8, 4'd7, 4'd5, 4'd7, 4'd7, 4'd7, 4'd8, 4'd10, 4'd10, 4'd10, 4'd10, 4'
    d8, 4'd10, 4'd6, 4'd7, 4'd10, 4'd7, 4'd3, 4'd10, 4'd11, 4'd3, 4'd8, 4'd6, 4'd8, 4'd8, 4'
    d13, 4'd10, 4'd6, 4'd8, 4'd11, 4'd9, 4'd6, 4'd6, 4'd10, 4'd10, 4'd8, 4'd9, 4'd9, 4'd11, 
    4'd8, 4'd0, 4'd1, 4'd6, 4'd1, 4'd11, 4'd7, 4'd7, 4'd10, 4'd8, 4'd8, 4'd10, 4'd8, 4'd9, 4
    'd5, 4'd10, 4'd8, 4'd9, 4'd8, 4'd1, 4'd4, 4'd9, 4'd10, 4'd6, 4'd8, 4'd9, 4'd9, 4'd7, 4'd
    5, 4'd3, 4'd8, 4'd4, 4'd3, 4'd5, 4'd10, 4'd8, 4'd9, 4'd6, 4'd8, 4'd9, 4'd10, 4'd11, 4'd9
    , 4'd10, 4'd10, 4'd8, 4'd8, 4'd6, 4'd9, 4'd10, 4'd5, 4'd8, 4'd9, 4'd8, 4'd9, 4'd9, 4'd9,
     4'd8, 4'd8, 4'd8, 4'd10, 4'd7, 4'd6, 4'd8, 4'd8, 4'd7, 4'd8, 4'd10, 4'd9, 4'd9, 4'd7, 4
    'd6, 4'd10, 4'd15, 4'd9, 4'd6, 4'd11, 4'd4, 4'd2, 4'd8, 4'd5, 4'd2, 4'd8, 4'd7, 4'd9, 4'
    d8, 4'd9, 4'd7, 4'd8, 4'd8, 4'd9, 4'd11, 4'd6, 4'd7, 4'd10, 4'd8, 4'd7, 4'd8, 4'd8, 4'd8
    , 4'd5, 4'd5, 4'd8, 4'd6, 4'd6, 4'd12, 4'd8, 4'd10, 4'd12, 4'd8, 4'd8, 4'd8, 4'd8, 4'd10
    , 4'd6, 4'd9, 4'd8, 4'd10, 4'd9, 4'd8, 4'd9, 4'd8, 4'd8, 4'd8, 4'd6, 4'd8, 4'd7, 4'd8, 4
    'd7, 4'd10, 4'd8, 4'd10, 4'd6, 4'd8, 4'd7, 4'd9, 4'd7, 4'd8, 4'd7, 4'd9, 4'd10, 4'd8, 4'
    d10, 4'd8, 4'd8, 4'd7, 4'd8, 4'd9, 4'd8, 4'd11, 4'd12, 4'd7, 4'd10, 4'd6, 4'd8, 4'd7, 4'
    d8, 4'd10, 4'd9, 4'd5, 4'd10, 4'd9, 4'd9, 4'd12, 4'd2, 4'd7, 4'd6, 4'd10, 4'd11, 4'd11, 
    4'd10, 4'd7, 4'd8, 4'd4, 4'd6, 4'd6, 4'd6, 4'd6, 4'd9, 4'd6, 4'd6, 4'd6, 4'd8, 4'd8, 4'd
    7, 4'd7, 4'd6, 4'd8, 4'd7, 4'd8, 4'd8, 4'd9, 4'd7, 4'd8, 4'd7, 4'd11, 4'd8, 4'd8, 4'd10,
     4'd6, 4'd10, 4'd6, 4'd7, 4'd8, 4'd9, 4'd8, 4'd7, 4'd7, 4'd9, 4'd6, 4'd8, 4'd10, 4'd5, 4
    'd7, 4'd8, 4'd7, 4'd7, 4'd10, 4'd10, 4'd10, 4'd6, 4'd0, 4'd5, 4'd10, 4'd0, 4'd6, 4'd7, 4
    'd8, 4'd6, 4'd8, 4'd10, 4'd6, 4'd9, 4'd7, 4'd6, 4'd8, 4'd11, 4'd9, 4'd7, 4'd8, 4'd15, 4'
    d6, 4'd8, 4'd9, 4'd6, 4'd8, 4'd7, 4'd7, 4'd4, 4'd4, 4'd7, 4'd7, 4'd8, 4'd8, 4'd9, 4'd8, 
    4'd8, 4'd8, 4'd10, 4'd7, 4'd8, 4'd9, 4'd10, 4'd6, 4'd10, 4'd8, 4'd7, 4'd8, 4'd6, 4'd10, 
    4'd9, 4'd8, 4'd8, 4'd7, 4'd7, 4'd8, 4'd8, 4'd10, 4'd9, 4'd9, 4'd10, 4'd6, 4'd8, 4'd6, 4'
    d8, 4'd8, 4'd9, 4'd7, 4'd11, 4'd8, 4'd1, 4'd6, 4'd0, 4'd0, 4'd0, 4'd8, 4'd7, 4'd2, 4'd9,
     4'd8, 4'd7, 4'd8, 4'd8, 4'd7, 4'd8, 4'd5, 4'd10, 4'd10, 4'd7, 4'd9, 4'd2, 4'd3, 4'd9, 4
    'd9, 4'd10, 4'd8, 4'd4, 4'd8, 4'd8, 4'd8, 4'd10, 4'd8, 4'd5, 4'd8, 4'd5, 4'd9, 4'd7, 4'd
    9, 4'd6, 4'd7, 4'd9, 4'd9, 4'd11, 4'd9, 4'd7, 4'd9, 4'd8, 4'd9, 4'd3, 4'd14, 4'd7, 4'd8,
     4'd8, 4'd7, 4'd9, 4'd6, 4'd9, 4'd7, 4'd10, 4'd9, 4'd10, 4'd7, 4'd11, 4'd7, 4'd9, 4'd6, 
    4'd8, 4'd9, 4'd6, 4'd12, 4'd8, 4'd8, 4'd8, 4'd6, 4'd11, 4'd10, 4'd4, 4'd9, 4'd5, 4'd10, 
    4'd8, 4'd9, 4'd5, 4'd8, 4'd10, 4'd9, 4'd10, 4'd4, 4'd9, 4'd10, 4'd11, 4'd6, 4'd7, 4'd0, 
    4'd15, 4'd7, 4'd9, 4'd6, 4'd7, 4'd8, 4'd9, 4'd8, 4'd7, 4'd7, 4'd7, 4'd7, 4'd15, 4'd7, 4'
    d9, 4'd7, 4'd7, 4'd8, 4'd12, 4'd10, 4'd8, 4'd7, 4'd8, 4'd10, 4'd8, 4'd8, 4'd7, 4'd7, 4'd
    10, 4'd3, 4'd8, 4'd8, 4'd7, 4'd6, 4'd8, 4'd8, 4'd7, 4'd7, 4'd8, 4'd7, 4'd6, 4'd8, 4'd7, 
    4'd7, 4'd8, 4'd8, 4'd7, 4'd9, 4'd7, 4'd4, 4'd9, 4'd8, 4'd9, 4'd11, 4'd9, 4'd8, 4'd9, 4'd
    8, 4'd9, 4'd8, 4'd8, 4'd5, 4'd14, 4'd11, 4'd6, 4'd8, 4'd9, 4'd8, 4'd10, 4'd9, 4'd9, 4'd1
    0, 4'd11, 4'd13, 4'd7, 4'd8, 4'd15, 4'd8, 4'd9, 4'd1, 4'd2, 4'd3, 4'd0, 4'd5, 4'd2, 4'd6
    , 4'd7, 4'd8, 4'd7, 4'd7, 4'd6, 4'd8, 4'd8, 4'd6
};
localparam signed [7:0] L1_B [0:7] = '{8'sd6, 8'sd6, -8'sd1, 8'sd0, 8'sd1, 8'sd5, 8'sd3, 8'sd4};
// Layer 2: 8 -> 1 channels, 72 MACs/pixel, shift 5
localparam integer L2_IN = 8;
localparam integer L2_OUT = 1;
localparam [3:0] L2_SHIFT = 4'd5;
// Weights are BIASED: stored u = w + 8, so 0..15 unsigned.
// Recover the signed weight as (u - 8), or use the
// decomposition sum(w*a) = sum(u*a) - 8*sum(a).
localparam [3:0] L2_W [0:71] = '{
    4'd9, 4'd6, 4'd9, 4'd6, 4'd4, 4'd7, 4'd8, 4'd8, 4'd12, 4'd8, 4'd8, 4'd7, 4'd9, 4'd9, 4'd
    3, 4'd7, 4'd11, 4'd10, 4'd8, 4'd10, 4'd9, 4'd9, 4'd10, 4'd9, 4'd9, 4'd10, 4'd7, 4'd8, 4'
    d8, 4'd7, 4'd7, 4'd6, 4'd9, 4'd7, 4'd9, 4'd6, 4'd10, 4'd9, 4'd8, 4'd5, 4'd12, 4'd7, 4'd7
    , 4'd8, 4'd9, 4'd7, 4'd5, 4'd6, 4'd8, 4'd10, 4'd11, 4'd7, 4'd10, 4'd8, 4'd11, 4'd5, 4'd9
    , 4'd5, 4'd11, 4'd8, 4'd8, 4'd9, 4'd7, 4'd10, 4'd10, 4'd5, 4'd8, 4'd9, 4'd5, 4'd7, 4'd5,
     4'd5
};
localparam signed [7:0] L2_B [0:0] = '{8'sd1};

// The whole payload as 253 x 12-bit config words, LSB first.
// 3028 significant bits.
localparam integer CFG_WORDS = 253;
localparam [11:0] DEF_CFG_WORDS [0:252] = '{
    12'hAC5, 12'h8B5, 12'h978, 12'h768, 12'h9A9, 12'h97A, 12'h78B, 12'h6BA, 12'h489, 12'hA47
    , 12'h935, 12'hCAA, 12'h77C, 12'h959, 12'h76B, 12'h9A9, 12'h9E8, 12'h727, 12'h9A9, 12'h5
    7A, 12'h768, 12'h878, 12'hAA9, 12'h879, 12'h002, 12'hFD0, 12'h3F7, 12'h040, 12'h1FB, 12'
    h720, 12'h59A, 12'h8A9, 12'h599, 12'hB85, 12'h9B9, 12'h399, 12'h598, 12'h497, 12'h088, 1
    2'h474, 12'h677, 12'hA8A, 12'h887, 12'h893, 12'h2A5, 12'hA65, 12'h8AA, 12'hA7C, 12'h4BA,
     12'h787, 12'h775, 12'hA87, 12'hAAA, 12'h6A8, 12'h7A7, 12'hBA3, 12'h683, 12'hD88, 12'h86
    A, 12'h69B, 12'hAA6, 12'h998, 12'h08B, 12'h161, 12'h77B, 12'h88A, 12'h98A, 12'h8A5, 12'h
    189, 12'hA94, 12'h986, 12'h579, 12'h483, 12'hA53, 12'h698, 12'hA98, 12'hA9B, 12'h88A, 12
    'hA96, 12'h985, 12'h998, 12'h889, 12'h7A8, 12'h886, 12'hA87, 12'h799, 12'hFA6, 12'hB69, 
    12'h824, 12'h825, 12'h897, 12'h879, 12'hB98, 12'hA76, 12'h878, 12'h588, 12'h685, 12'h8C6
    , 12'h8CA, 12'h888, 12'h96A, 12'h9A8, 12'h898, 12'h688, 12'h878, 12'h8A7, 12'h86A, 12'h7
    97, 12'h978, 12'hA8A, 12'h788, 12'h898, 12'h7CB, 12'h86A, 12'hA87, 12'hA59, 12'hC99, 12'
    h672, 12'hBBA, 12'h87A, 12'h664, 12'h966, 12'h666, 12'h788, 12'h867, 12'h887, 12'h879, 1
    2'h8B7, 12'h6A8, 12'h76A, 12'h898, 12'h977, 12'hA86, 12'h875, 12'hA77, 12'h6AA, 12'hA50,
     12'h760, 12'h868, 12'h96A, 12'h867, 12'h79B, 12'h6F8, 12'h698, 12'h778, 12'h744, 12'h88
    7, 12'h889, 12'h7A8, 12'hA98, 12'h8A6, 12'h687, 12'h89A, 12'h778, 12'hA88, 12'hA99, 12'h
    686, 12'h988, 12'h8B7, 12'h061, 12'h800, 12'h927, 12'h878, 12'h878, 12'hAA5, 12'h297, 12
    'h993, 12'h48A, 12'h888, 12'h58A, 12'h958, 12'h697, 12'h997, 12'h79B, 12'h989, 12'h7E3, 
    12'h788, 12'h969, 12'h9A7, 12'hB7A, 12'h697, 12'h698, 12'h88C, 12'hB68, 12'h94A, 12'h8A5
    , 12'h859, 12'hA9A, 12'hA94, 12'h76B, 12'h7F0, 12'h769, 12'h898, 12'h777, 12'h7F7, 12'h7
    79, 12'hAC8, 12'h878, 12'h88A, 12'hA77, 12'h883, 12'h867, 12'h778, 12'h678, 12'h778, 12'
    h788, 12'h479, 12'h989, 12'h89B, 12'h989, 12'h588, 12'h6BE, 12'h898, 12'h99A, 12'hDBA, 1
    2'hF87, 12'h198, 12'h032, 12'h625, 12'h787, 12'h867, 12'h668, 12'h060, 12'h0FF, 12'h010,
     12'h305, 12'h040, 12'h693, 12'h469, 12'h887, 12'h88C, 12'h997, 12'hB73, 12'hA8A, 12'hA9
    9, 12'hA99, 12'h887, 12'h677, 12'h979, 12'h9A6, 12'hC58, 12'h877, 12'h579, 12'hA86, 12'h
    A7B, 12'h5B8, 12'hB59, 12'h988, 12'hAA7, 12'h985, 12'h575, 12'h015, 12'h005
};

`endif
